spring:

  profiles:
    active: prod

  application:
    name: auth-microservice

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: useruser
    password: userpass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true

jwt:
  secret: ${JWT_SECRET}

